### ISSUE TITLE
The given DECA headposes points don't match

### ISSUE THREAD

**Issue by ligenjie** [NetEase-GameAI/Face2FaceRHO#15]
The offical DECA model outputs 68 2D points from one face.Your own 3DMM has 72 2D points.I think data/landmark_embedding.json is your model point-choose projection...How can I project DECA offical 68 points to 72points.I run the test_case/source.jpg with offical DECA model and then compare the offical 68 points and your project 72 points of 'source.jpg'. I can't find the projection of this two files.

**Comment by NetEase-GameAI** [comment]
Yes. The landmark_embedding.json is our model point-choose projection.  You can't directly project the original 68 points to our 72 points, because all the 72 points are now re-selected on the model.  We re-write the vertices2landmarks function in the FLAME.py, and get 72 points based on landmark_embedding.json.

**Comment by ligenjie** [comment]
Yep! I get that. But I have another problem.I run the fitting.py several times using the same pic(test_case/source.jpg) by your DECA model.Every time I get different headposes and landmark values.If there any random causes the differences?

**Comment by NetEase-GameAI** [comment]
emmmm, there is no random in the fitting process. Perhaps you use the JPEG image, the decoder of JPEG may be different between different packages, try using a png image.

**Comment by ligenjie** [comment]
Thank u~
