### ISSUE TITLE
poor result

### ISSUE THREAD

**Issue by SEUvictor** [NetEase-GameAI/Face2FaceRHO#9]
![30](https://user-images.githubusercontent.com/73874553/182325765-480f158f-e8d3-4fcf-9b85-5fd8e7d54e25.png)
I use this picture above as the source image.
![driving](https://user-images.githubusercontent.com/73874553/182326023-226a9d3e-1a11-4d71-a7f6-5595eaa44a8d.png)
and use this picture above as the driving image.
The character features are relatively similar, but the result is very poor.Like the following figure.
![result](https://user-images.githubusercontent.com/73874553/182326627-cd77ca4c-4107-43cc-8bbe-42e9986047d8.png)
If the source image remains unchanged, the driving image is changed to the following figure.
![driving2](https://user-images.githubusercontent.com/73874553/182327166-20ba9e5f-0f6d-4593-a9b5-3ae57668875f.png)
The result becomes worse, as shown in the following figure.
![result2](https://user-images.githubusercontent.com/73874553/182327455-578d5cde-41d0-4065-a15a-5d6efbefd423.png)

**Comment by SEUvictor** [comment]
Is it my mistake? I operate like this.
1.run fitting.py to get src_headpose.txt/src_landmark.txt/drv_headpose.txt/drv_landmark.txt.
2.run reenact.py and use txt files above to get the final reenacted result.

**Comment by NetEase-GameAI** [comment]
I think you refer to the the expression transfer seems weak. This is partly because of the use DECA 3DMM fitting method. If using our 3DMM fitting method, the preformance would be better. Addiontionaly, our currently result cannot reproduce the eyebrow movement due to the limitation of 3DMM fitting. It is also worth to note that we have already achieved SOTA performance on high-resolution images in real-time on the oneshot track. And all the existing methods cannot reproduce the winkle caused by expression change based on only one input image.

**Comment by NetEase-GameAI** [comment]
I think you refer to the expression transfer seems weak. This is partly because of the use DECA 3DMM fitting method. If using our 3DMM fitting method, the performance would be better. Additionally, our current method cannot reproduce the eyebrow movement due to the limitation of 3DMM fitting. It is also worth noting that we have already achieved SOTA performance on high-resolution images in real-time on the one-shot track. And all the existing methods cannot reproduce the winkle caused by expression change based on only one input image.

**Comment by SEUvictor** [comment]
> 

Please allow me to confirm again.
Is the "src_header.txt/src_landmark.txt/drv_header.txt/drv_landmark.txt" of the source image and the driving image obtained through "fitting.py"? And if it is a driving video, the txt files of each frame should also be obtained through "fitting.py"?

**Comment by NetEase-GameAI** [comment]
yes! you are right!
